### ISSUE TITLE
how to load image

### ISSUE THREAD

**Issue by growvv** [wzshiming/fake-k8s#109]
Is there a command similar to "kind load"? I need to load a local image to the cluster

**Comment by wzshiming** [comment]
The fake clusters can use host local images, no need to load local images. What are your specific usage scenarios?

**Comment by growvv** [comment]
My current scene is:
```bash
kind load docker-image xxx-image:latest
kubectl apply -f  xx.yaml
```
```yaml
containers:
        - name: my-image
          image: xxx-image
          imagePullPolicy: IfNotPresent
```
I want to use fake-k8s instead of kind, but I don't know how to do it
